### PR TITLE
Finitize garbitrary

### PR DESCRIPTION
**Pull request by fisx**
See source code comment.

Sorry about the aggressive style change.  If you prefer, I am happy to revert that into one 112-char line.

### CODE REVIEW

**Comment by np** [comment]
I've ran into troubles even with this version. The case was a recursive tree of comments which was blowing up during our test suite. I've tried other strategies:
- `max 0 . subtract 100`: worked but it seems to fragile to me
- `\s -> s - (s `div` 10)`: didn't worked even with `3` instead of `10`
- `(`div` 3)`: seems to work reliably

I would suggest exporting a `garbitrary` function taking the scaling function as a parameter and also picking a more conservatively safe scaling such as `(`div` 3)`.

**Comment by fisx** [comment]
@np: thanks, I implemented your suggestions.

**Comment by andorp** [comment]
- Relevant paper on this topic: [Generating Constrained Random Data with Uniform Distribution](http://publications.lib.chalmers.se/records/fulltext/195847/local_195847.pdf)
- Implementation with other generics library: https://github.com/Lysxia/generic-random

**Comment by kosmikus** [comment]
Sorry for the long delay. I'm undecided here. Yes, a "correct" solution would probably be best, but is not in scope for this package if it is more than a few lines of code.

But I'm also reluctant to replace one broken mechanism by another that is also broken. In my experience, uniform scaling of all subterms is not in general what you want. Also, I fail to see how this new version is even using the scaling factor ...

**Comment by fisx** [comment]
@kosmikus don't worry about the response time, this is low priority.

You may be right about the lack of scaling, but before I take a look, i think we should decide on the conditions on which this can be merged.

In my opinion, a useful implementation generates _some_ good test cases and terminates.  If you think that the test cases generated here are not good enough, I don't want to fight and we can just keep the generic implementation in our own code base for now.

Note that @andorp also implemented a generic shrink, which also has its peculiarities but potentially makes this patch more useful.

https://github.com/liqd/aula/blob/7e06c5492be1fce643ac84ce05349b2bb979fea0/src/Arbitrary.hs#L107

**Comment by andorp** [comment]
@kosmikus Should I create a new PR for the shrink?

**Comment by kosmikus** [comment]
I am not entirely sure what to do here. The whole `basic-sop` package is admittedly a bit strange. It's supposed to contain some lightweight examples of using SOP. If we want a sophisticated function for deriving proper QuickCheck instances, I'm all in favour of creating `quickcheck-sop` for this purpose, which then also has the freedom of introducing additional dependencies etc.

For this package, I'm not exactly sure where to draw the line. If you think it makes sense to include a slightly more sophisticated arbitrary and to include some form of shrinking, you may be able to convince me.

**Comment by edsko** [comment]
Closing this since the last comment has been 7 years ago :) Feel free to reopen if some resolution can be reached :)

**Pull request closed without merging**
